config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index, :create, :new, :edit, :show, :update]
  post '/items/:id/sign_up', to: 'items#sign_up', as: 'sign_up'
  post '/items/:id/password', to: 'items#input_password', as: 'item_input_password'
  post '/items/:id/remove', to: 'items#remove', as: 'item_remove'
  get '/emails/:id/:verification_token', to: 'emails#verify', as: 'verify'
  get '/emails/:id/:verification_token/remove', to: 'emails#remove', as: 'remove'
  root to: 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :item
  has_many :send_logs
  before_create :set_defaults
  validates :item, presence: true
  validate :item_not_ended

  def verify
    self.verified = true
    save
  end

  def send_verification
    # we don't want adversaries to be able to determine whether an email is signed up for something
    # but we also don't want to enable any send-pizza attacks
    # so if you've tried to sign up three times already in the last 24 hours it'll fail silently
    # this could maybe be done better but it'll do for now #agile
    return unless can_send?
    UserMailer.verification_email(self).deliver_later
  end

  def send_removal_request
    return unless verified && can_send?
    UserMailer.removal_email(self).deliver_later
  end

  def send_success_msg
    UserMailer.success_email(self).deliver_later unless sent_success_msg
    update(sent_success_msg: true)
  end

  private

    def can_send?
      SendLog.where(email: self, created_at: (24.hours.ago..Time.now)).count < 3
    end

    def set_defaults
      self.verification_token = SecureRandom.hex
      self.verified = false
    end

    def item_not_ended
      if item && item.end_date && item.end_date == Date.today
        errors.add(:item_end_date, "can't be today")
      elsif item && item.end_date && item.end_date < Date.today
        errors.add(:item_end_date, "can't be in the past")
      end
    end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :emails, dependent: :destroy
  validates :threshold, numericality: { greater_than: 0 }
  validates :title, :success_msg, presence: true
  validate :end_date_not_in_past

  has_secure_password

  def verified_signups
    emails.where(verified: true)
  end

  def succeeded?
    if verified_signups.count >= threshold
      verified_signups.where(sent_success_msg: false).find_each(&:send_success_msg)
      return true
    end
    false
  end

  def sign_up(email_txt)
    email = Email.find_by(email: email_txt, item_id: id)
    if email
      email.send_verification
      return true
    else
      email = Email.new(email: email_txt, item_id: id)
      if email.save
        email.send_verification
        return true
      end
    end
    false
  end

  def ended?
    end_date && end_date <= Date.today
  end

  private

    def end_date_not_in_past
      if end_date.present? && end_date == Date.today
        errors.add(:end_date, "can't be today")
      elsif end_date.present? && end_date < Date.today
        errors.add(:end_date, "can't be in the past")
      end
    end
end

app/models/send_log.rb
class SendLog < ApplicationRecord
  belongs_to :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email

  def verify
    if @email && @email.verify
      item = @email.item
      item.succeeded?
      redirect_to item_url(item), notice: 'Verified'
    else
      redirect_to items_url, notice: 'Error - can\'t verify'
    end
  end

  def remove
    if @email
      item = @email.item
      @email.destroy
      redirect_to item_url(item), notice: 'You have been removed from this item'
    else
      redirect_to items_url, notice: 'Error - can\'t remove this email'
    end
  end

  private

    def set_email
      @email = Email.find_by(id: params[:id], verification_token: params[:verification_token])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update]
  before_action :check_edit_authorization, only: [:edit, :update]

  # GET /items
  def index
    @items = Item.where(public: true).order('created_at DESC').page(params[:page] || 1)
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  def sign_up
    item = Item.find(params[:id])
    if item.sign_up(params[:email])
      redirect_to item_url(params[:id]), notice: 'Signed up - verify your email'
    else
      redirect_to item_url(params[:id]), notice: 'Error'
    end
  end

  def input_password
    @item = Item.find(params[:id])
    if @item.authenticate(params[:password])
      session[:current_edit] = @item.id
      redirect_to edit_item_url(params[:id])
    else
      redirect_to item_url(params[:id]), notice: 'Wrong password'
    end
  end

  # POST /items
  def create
    item_params = item_create_params
    item_params[:end_date] = end_date
    @item = Item.new(item_params)
    @item.password = params[:item][:password]
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    item_params = item_update_params
    item_params[:end_date] = end_date
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def remove
    email = Email.find_by(email: params[:email_remove], item_id: params[:id])
    email.send_removal_request if email
    redirect_to items_url, notice: 'A removal request has been sent, '\
      'if your email was signed up and verified for the item. If not, nothing has happened.'
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_update_params
      params.require(:item).permit(:success_msg, :public, :show_threshold, :show_verified_signups)
    end

    def item_create_params
      params.require(:item).permit(:title, :description, :threshold,
                                   :success_msg, :public, :show_threshold,
                                   :show_verified_signups)
    end

    def end_date
      return unless params[:item][:end_date_enabled] != '0'
      Date.new(params[:item]['end_date(1i)'].to_i,
               params[:item]['end_date(2i)'].to_i,
               params[:item]['end_date(3i)'].to_i)
    end

    def check_edit_authorization
      return unless !session[:current_edit] || session[:current_edit] != params[:id].to_i
      redirect_to item_url(params[:id]), notice: 'You aren\'t authorized to edit this item'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if mode == :new %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :item_title %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :item_description %>
    </div>

    <div class="field">
      <%= form.label :threshold %>
      <%= form.number_field :threshold, id: :item_threshold, min: 1 %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.text_field :password, id: :item_password %>
    </div>
  <% elsif mode == :edit %>
    <div class="not-field">
      Title: <%= @item.title %>
    </div>

    <div class="not-field">
      Description: <%= @item.description %>
    </div>

    <div class="not-field">
      Threshold: <%= @item.threshold %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public, id: :item_public %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.check_box :end_date_enabled, id: :item_end_date_enabled, checked: !(@item.end_date.nil?) %>
    <div id='end_date_select_container'>
      <%= form.date_select :end_date, id: :end_date, default: 1.year.from_now %>
    </div>
    <script type='text/javascript'>
      var endDateCheckbox = document.getElementById('item_end_date_enabled');
      var endDateContainer = document.getElementById('end_date_select_container');
      if (!endDateCheckbox.checked) {
        endDateContainer.className = 'invis';
      }
      endDateCheckbox.addEventListener('change', function () {
        if (this.checked) {
          endDateContainer.className = '';
        } else {  
          endDateContainer.className = 'invis';
        }
      })
    </script>
  </div>

  <div class="field">
    <%= form.label :show_threshold %>
    <%= form.check_box :show_threshold, id: :item_show_threshold %>
  </div>

  <div class="field">
    <%= form.label :show_verified_signups %>
    <%= form.check_box :show_verified_signups, id: :item_show_verified_signups %>
  </div>

  <div class="field">
    <%= form.label :success_msg %>
    <%= form.text_area :success_msg, id: :item_success_msg %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Stats</h1>
This item has <%= @item.verified_signups.count %> verified signups.

<h1>Edit</h1>

<%= render 'form', item: @item, mode: :edit %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.title, item %></td>
        <td><%= item.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

<%= paginate @items %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item, mode: :new %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
	<% if @item.show_threshold %>
		<strong>Threshold:</strong> <%= @item.threshold %>
	<% end %>
	<% if @item.show_verified_signups %>
		<strong>Verified signups:</strong> <%= @item.verified_signups.count %>
	<% end %> 
</p>


<% unless @item.ended? %>
	<%= form_tag({controller: 'items', action: 'sign_up', id: @item.id}, method: 'post') do %>
	<p><strong>Add your email:</strong>

		<%= text_field_tag :email %>
		<%= submit_tag "Sign up" %>
	<% end %>
<% else %>
	This item has ended and is no longer open for signup.
<% end %>

<%= link_to 'Back', items_path %>

<%= form_tag({controller: 'items', action: 'input_password', id: @item.id}, method: 'post') do %>
	Enter password to edit: 
	<%= text_field_tag :password %>
	<%= submit_tag "Submit" %>
<% end %>

<%= form_tag({controller: 'items', action: 'remove', id: @item.id}, method: 'post') do %>
	If you're signed up for this item and want to remove yourself from it, enter your email here:
	<%= text_field_tag :email_remove, nil, { id: 'email_remove' } %>
	<%= submit_tag "Send removal request" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actuator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>